---
sidebar: sidebar 
permalink: qsg.html 
keywords: QSG, ONTAP tools for VMware vSphere, Quick start guide, Installing 
summary: 提供有关部署和初始化适用于 VMware vSphere 的 ONTAP 工具的说明。 
---
= 适用于 VMware vSphere 的 ONTAP 工具快速入门
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
适用于VMware vSphere的ONTAP工具是一个vCenter Server插件、其中包括ONTAP工具、VASA Provider和Storage Replication Adapter (SRA)扩展。建议对所有ONTAP vSphere环境使用ONTAP工具、因为它会根据最佳实践配置ESXi主机设置和配置ONTAP存储。要支持虚拟卷（ VVOL ），需要使用 VASA Provider ，而 SRA 可与 VMware Site Recovery Manager 配合使用。



== 准备安装

您可以将此插件部署为虚拟设备，这样可以减少在 vCenter Server 中单独安装和注册每个产品的工作量。



=== 部署要求

ONTAP 工具可与VMware vCenter Server虚拟设备(vCSA)结合使用。您必须在包含 ESXi 系统的受支持 vSphere 上部署 ONTAP 工具。

最小空间和主机规模估算要求如下：

[cols="25,75"]
|===
| * 系统 * | * 最低要求 * 


| 空间 | 2.1 GB 用于精简配置安装， 54.0 GB 用于厚配置安装 


| 主机规模估算 | 建议内存： 12 GB ，建议 CPU ： 2 
|===
您应了解以下许可证：

[cols="25,75"]
|===
| * 许可证 * | * 问题描述 * 


| SnapMirror | （可选）如果您使用 VVol 复制，则需要对 SRA 和 VASA Provider 执行故障转移操作。 


| FlexClone | （可选）对于对 SRA 执行测试故障转移操作以及对 VASA Provider 执行 VVOL 操作都是必需的。 
|===
ONTAP 工具使用以下默认双向 TCP 端口：

|===


| * 其他要求 * | * 问题描述列 * 


 a| 
9083.
 a| 
启用后， VASA Provider 和 Storage Replication Adapter （ SRA ）均使用此端口与 vCenter Server 进行通信。要获取 TCP/IP 设置，也需要此端口。此端口用于下载VP支持包、访问Web-CLI用户界面以及控制从VMware到VP的通信路径。



 a| 
443.
 a| 
根据凭据的配置方式， VMware vCenter Server 和存储系统会侦听此端口上的安全通信。此端口用于客户端-服务器通信架构。默认情况下、安全连接会启用443端口。此客户端可以是使用REST API的任何自动化客户端、它会启动与服务器的连接、并且端点会交换数据。



 a| 
8143
 a| 
ONTAP工具会侦听此端口上的安全通信。此端口用于客户端-服务器通信架构。此客户端可以是使用REST API的任何自动化客户端、它会启动与服务器的连接、并且端点会交换数据。此端口可用于ONTAP工具服务和导出ONTAP工具服务器日志。register.html页面托管在此端口上。REST Swagger将在此端口上公开。



 a| 
8443
 a| 
此端口用于远程插件服务。

|===
最低存储和应用程序要求：

|===
| * 存储，主机和应用程序 * | * 版本要求 * 


| ONTAP | ONTAP 9.7、9.8P1或更高版本。 


| VMware vSphere ， vCenter Server ， ESXi 主机， Site Recovery Manager （ SRM ），插件应用程序和数据库列 1 | 请参见 https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["互操作性表工具"^] 
|===


=== ONTAP 工具要求

* 配置和设置 vCenter Server 环境。
* 下载 .ova 文件。
* vCenter Server 实例的登录凭据。
* 删除浏览器缓存以避免在部署 ONTAP 工具期间出现任何浏览器缓存问题描述。
* 配置虚拟设备响应 ICMP ping 所使用的默认网关。
* 虚拟设备的有效 DNS 主机名。




=== SRA 的可选要求

如果要部署虚拟设备以与VMware Site Recovery Manager结合使用、则必须事先：*下载 `.tar.gz` 文件。



== 部署 ONTAP 工具

.步骤
. 下载 `.zip` 包含中的二进制文件和签名证书的文件 https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp 支持站点"^] 连接到 vSphere Client 系统以部署 ONTAP 工具。
. 提取 `.zip` 归档并部署 `.ova` 文件
+
如果要部署 SRA ，则必须在源站点和目标站点上部署 ` 。 ova` 文件。

. 登录到vSphere Web Client、选择*主页*>*主机和群集*。
. 右键单击所需数据中心，然后单击 * 部署 OVF 模板 * 。
+
如果您使用的是vCenter7.0u3e及更高版本、请执行以下操作、否则请继续执行步骤5。这是一个可选步骤、用于验证OVA二进制文件完整性是否未被篡改。

+
** 从NetApp 支持站点 下载_OTV_inter_root_CERT_chain.pem_文件。
** 导航到*vCenter*>*管理*>*证书管理*。
** 单击*添加可信根证书*选项。
** 单击*Browse*并提供_OTV_inter_root_CERT_chain.pep_文件的路径。
** 单击 * 添加 * 。
+

NOTE: 消息Entrust Code signing - OVCS2 (Trusted certificATE)用于确认下载的OVA文件的完整性。如果看到Entrust代码签名- OVCS2 (证书无效)消息、请将VMware vCenter Server升级到7.0U3E或更高版本。



. 您可以输入 .ova 文件的 URL ，也可以浏览到保存 .ova 文件的文件夹，然后单击 * 下一步 * 。
. 输入所需详细信息以完成部署。



NOTE: （可选）如果要在不向 vCenter Server 注册的情况下创建容器，请在配置 vCenter 或启用 VCF 部分中选中启用 VMware Cloud Foundation （ VCF ）复选框。

您可以从 * 任务 * 选项卡查看部署进度，并等待部署完成。

在部署过程中、会执行校验和验证。如果部署失败、请执行以下操作：

. 验证vpserver/logs/校 验和.log。如果显示"Checksum verification failed (校验和验证失败)"、则可以在同一日志中看到失败的JAR的验证。
+
日志文件包含执行_na256sum -c /opt/NetApp/vpserver/conf/checksosqupsu_。

. 验证vscserver/log/校 验和.log。如果显示"Checksum verification failed (校验和验证失败)"、则可以在同一日志中看到失败的JAR的验证。
+
日志文件包含执行_sc256sum -c /opt/NetApp/vscserver/etc/checksosqu并且





=== 在 SRM 上部署 SRA

您可以在 Windows SRM 服务器或 8.2 SRM 设备上部署 SRA 。



==== 在 SRM 设备上上传和配置 SRA

.步骤
. 从下载 ` .tar.gz` 文件 https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp 支持站点"^]。
. 在 SRM 设备屏幕上，单击 * 存储复制适配器 * > * 新适配器 * 。
. 将 ` .tar.gz` 文件上传到 SRM 。
. 重新扫描适配器以验证是否已在 "SRM Storage Replication Adapter" 页面中更新详细信息。
. 使用管理员帐户使用 putty 登录到 SRM 设备。
. 切换到 root 用户： `su root`
. 在日志位置输入命令以获取 SRA Docker 使用的 Docker ID ： `docker ps -l`
. 登录到容器 ID ： `docker exec -it -u SRM <container id> sh`
. 使用ONTAP 工具IP地址和密码配置SRM： `perl command.pl -I <otv-IP> administrator <otv-password>`此时将显示一条成功消息，确认存储凭据已存储。




==== 正在更新 SRA 凭据

.步骤
. 使用以下命令删除 /SRM/SRA 目录的内容：
+
.. `cd /SRM/SRA / conf`
.. `rm -rf *`


. 执行 perl 命令以使用新凭据配置 SRA ：
+
.. `cd /SRM/SRA /`
.. `perl command.pl -I <otv-IP> administrator <otv-password>`






==== 启用 VASA Provider 和 SRA

.步骤
. 使用在OVA ONTAP 工具部署期间提供的vCenter IP登录到vSphere Web Client。
. 在快捷方式页面中，单击插件部分下的*NetApp ONTAP tools*。
. 在ONTAP 工具的左窗格中，选择*Settings > Administrative Settings > Manage Capabilities*，然后启用所需的功能。
+

NOTE: 默认情况下， VASA Provider 处于启用状态。如果要对 VVOL 数据存储库使用复制功能，请使用启用 VVOL 复制切换按钮。

. 输入 ONTAP 工具的 IP 地址和管理员密码，然后单击 * 应用 * 。

