---
permalink: deploy/concept_configure_your_storage_system_environment.html 
sidebar: sidebar 
keywords:  
summary: 适用于 VMware vSphere 的 ONTAP 工具提供了一种发现存储系统和设置存储凭据的机制。这些凭据提供了ONTAP工具用户使用存储系统执行任务所需的ONTAP权限。 
---
= 为VMware vSphere存储系统配置ONTAP 工具
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
适用于 VMware vSphere 的 ONTAP ® 工具提供了一种发现存储系统和设置存储凭据的机制。这些凭据提供了ONTAP工具用户使用存储系统执行任务所需的ONTAP权限。

在ONTAP工具显示和管理存储资源之前、ONTAP工具必须先发现存储系统。在发现过程中，您必须提供存储系统的 ONTAP 凭据。这些特权（或角色）与分配给每个存储系统的用户名和密码对关联。这些用户名和密码对使用 ONTAP 基于角色的访问控制（ Role-Based Access Control ， RBAC ），必须在 ONTAP 中进行设置。您不能在ONTAP工具中更改这些凭据。您可以使用 ONTAP 系统管理器定义 ONTAP RBAC 角色。


NOTE: 如果您以管理员身份登录，则会自动拥有该存储系统的所有特权。

将存储系统添加到ONTAP工具时、必须提供存储系统的IP地址以及与该系统关联的用户名和密码对。您可以设置ONTAP工具在存储系统发现过程中要使用的默认凭据、也可以在发现存储系统后手动输入凭据。添加到ONTAP工具中的存储系统详细信息会自动推送到您在部署中启用的扩展。您无需手动向 VASA Provider 和 Storage Replication Adapter （ SRA ）添加存储。ONTAP工具和SRA均支持在集群级别和Storage Virtual Machine (SVM)级别添加凭据。VASA Provider 仅支持使用集群级别的凭据来添加存储系统。添加存储系统时、ONTAP 工具插件与存储系统之间的任何通信都应进行相互身份验证。

如果您的环境包含多个vCenter Server实例、则在通过存储系统页面向ONTAP工具添加存储系统时、添加存储系统对话框会显示一个vCenter Server框、您可以在其中指定要将存储系统添加到哪个vCenter Server实例。如果您通过右键单击数据中心名称来添加存储系统，则无法指定 vCenter Server 实例，因为服务器已与该数据中心关联。

发现可通过以下方式之一进行。在每种情况下，您都必须为任何新发现的存储系统提供凭据。

* 当ONTAP工具服务启动时、ONTAP工具将开始其自动后台发现过程。
* 您可以单击存储系统页面中的*重新发现全部*按钮，也可以单击主机或数据中心，从*操作*菜单(*操作*>*NetApp ONTAP 工具*>*更新主机和存储数据*)中选择该按钮。您也可以单击概述部分的入门选项卡上的 * 发现 * 。


所有ONTAP工具功能都需要特定权限才能执行任务。您可以根据与 ONTAP 角色关联的凭据限制用户可以执行的操作。具有相同存储系统用户名和密码对的所有用户都共享一组相同的存储系统凭据，并可执行相同的操作。
