---
permalink: deploy/concept_installation_workflow_for_existing_users_of_ontap_tools.html 
sidebar: sidebar 
keywords:  
summary: 适用于 VMware vSphere 的 ONTAP 工具 9.x 版支持原位升级到最新版本。 
---
= 适用于现有 ONTAP 工具用户的部署工作流
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
适用于 VMware vSphere 的 ONTAP 工具 9.x 版支持原位升级到最新版本。

Virtual Storage Console 6.x ， Storage Replication Adapter 2.x ， 3.x ， 4.x 和 VASA Provider 6.x 等各个应用程序的早期版本使用不同的升级过程。如果您在设置中安装了这些旧版本的 VSC ， VASA Provider 或 SRA ，则应执行以下操作：

. 部署最新版本的 ONTAP 工具。
. 迁移任何现有配置数据。
+
配置数据包括存储系统凭据以及在 `kaminoprefs.xml` 和 `vscPreferences.xml` 文件中找到的首选项。



link:../configure/reference_set_ipv4_or_ipv6.html["使用首选项文件设置 IPv4 或 IPv6"]

在许多情况下，您可能不需要迁移配置数据。但是，如果您之前已自定义了首选项文件，则可能需要查看这些文件并对新部署的 ONTAP 工具进行类似的更改。您可以将存储系统添加到新部署的ONTAP 工具中、并在添加时指定凭据。

如果要从 VASA Provider 6.X 升级，则应在升级之前取消注册 VASA Provider 。有关详细信息，请参见当前版本的文档。

如果要从SRA 4.0或更早版本升级：

* 如果您使用的是 SRA 4.0P1 ，则必须先升级到 SRA9.6 ，然后再原位升级 SRA 9.6 版。您可以稍后升级到最新版本的 ONTAP 工具。
+
link:../deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html["升级到最新版本的 ONTAP 工具"]

* 如果您使用的是 SRA 2.1 或 3.0 ，则应首先记下现有站点配置详细信息。
+
适用于ONTAP 版本的Storage Replication Adapter (SRA) 4.0也会使用VASA Provider、因此您必须取消注册VASA Provider、然后部署最新版本的ONTAP 工具。服务器的先前版本 (`.ova`)、可以在升级完成后删除。



如果您已部署 VASA Provider ，则在从现有设置升级后，必须使用 `编辑设置` 选项将 ONTAP 工具的内存大小配置为 12 GB 。您还必须修改虚拟内存预留。要修改内存大小，必须关闭虚拟机。

如果您拥有 VSC ， VASA Provider 和 SRA 虚拟设备 7.2 或 7.2.1 版，则无法直接升级到统一设备的 9.7P1 或更高版本。您必须先将现有设置升级到虚拟设备 9.7 版，然后再升级到最新版本。

要升级到ONTAP 工具9.10及更高版本、您应运行虚拟设备9.7P1或更高版本。不支持从虚拟设备 9.7P1 之前的早期版本升级。

如果您要部署最新版本的ONTAP 工具、则必须查看相关主题 link:../deploy/concept_space_and_sizing_requirements_for_ontap_tools_for_vmware_vsphere.html["ONTAP 工具的空间和规模估算要求"]。主题 link:../deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html["升级到最新版本的 ONTAP 工具"] 具有有关执行原位升级的信息。

* 相关信息 *

https://mysupport.netapp.com/site/tools[]
