---
permalink: deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords: Virtual Storage Console, Storage Replication Adapter 
summary: 您可以按照此处提供的说明、从现有9.10或更高版本设置原位升级到最新版本的ONTAP 工具。 
---
= 升级到最新版本的 ONTAP 工具
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以按照此处提供的说明、从现有9.10或更高版本原位升级到ONTAP 工具的最新版本。

* 您需要的内容 *

* 您必须已下载最新版本 ONTAP 工具的 _.ISO_ 文件。
* 您必须至少预留 12 GB RAM ， ONTAP 工具才能在升级后以最佳状态运行。
* 您必须清理 vSphere Client 浏览器缓存。
+
link:../deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html["清除 vSphere 缓存的已下载插件软件包"]



如果需要、请执行以下步骤来验证_.ISO_文件。这是一个可选步骤：

. 从Entrust (OTV_ISO_CERT.pem)中颁发的代码签名证书中提取公共密钥openssl x509 -in OTV_ISO_CERT.pem -pubkey -nooout > Csc-prod-OTV-SRA-TGZ.pub
. 使用公共密钥验证摘要中的签名(此步骤应在安装二进制文件之前在最终用户系统中进行。证书包应包含在部署包中)
+
OpenSSL dgst -SHA256 -verifyCcs-prod-OTV-SRA-TGZ.pub -Signature NetApp-ONATP-tools-for VMware-vSphere 9.12-9327-upgrade iso.SIG netapp-ontap-tools-for-vmware-vsphere-9.12-9327-upgrade.iso



升级后，现有部署中 VASA Provider 的状态将保留下来。升级后，您应根据需要手动启用或禁用 VASA Provider 。但是，即使未使用 VMware 虚拟卷（ VVOL ），最好启用 VASA Provider ，因为它可以为传统数据存储库配置启用存储功能配置文件并发出存储警报。


NOTE: 您只能从现有9.10或更高版本原位升级到ONTAP 工具的最新版本。


NOTE: 从ONTAP tools 9.12升级开始、所有存储系统的身份验证和通信过程都会通过自动信任ONTAP存储证书从基本身份验证更改为基于证书的身份验证。无需用户执行任何操作。

添加不带证书身份验证的存储系统受到限制。

如果使用json文件添加了具有自定义创建的集群范围用户的存储系统、而您希望升级到9.12及更高版本、则
升级之前、请在ONTAP命令行界面上运行以下命令、以便在适用于VMware vSphere的ONTAP工具与ONTAP之间启用基于证书的通信。

. _security login Role create -Role <existing-role-name>-cmddirname "security login show"-access all_
. _security login Role create -Role <existing-role-name>-cmddirname "security certificat show"-access all_
. _security login Role create -Role <existing-role-name>-cmddirname "security certificat install"-access all_


如果使用json文件使用自定义创建的SVM范围用户添加存储系统、而您要升级到9.12及更高版本、则
升级之前、在具有集群管理员访问权限的ONTAP命令行界面上运行以下命令、以便在适用于VMware vSphere的ONTAP工具与ONTAP之间启用基于证书的通信：

. _security login Role create -Role <existing-role-name>-cmddirname "security certificat install"-access all -vserver <vserver-name>_
. _security login Role create -Role <existing-role-name>-cmddirname "security certificat show"-access all -vserver <vserver-name>_
. _security login create -user-or-group-name <user>-application http -authentication方法cert -Role <existing-role-name>-vserver <vserver-name>_
. _security login create -user-or-group-name <user>-application ontapi -authentication方法cert -Role <existing-role-name>-vserver <vserver-name>_


* 步骤 *

. 将下载的 _.ISO_ 文件挂载到 ONTAP 工具：
+
.. 单击 * 编辑设置 * > * DVD/CD-ROM 驱动器 * 。
.. 从下拉列表中选择 * 数据存储 ISO 文件。
.. 浏览并选择已下载的 _.ISO_ 文件，然后选中 * 启动时连接 * 复选框。


. 访问已部署 ONTAP 工具的摘要选项卡。
. 启动维护控制台。
. 在 `M菜单` 提示符处，为 * 系统配置 * 输入选项 `2` ，然后为 * 升级 * 输入选项 `8` 。
+
升级完成后， ONTAP 工具将重新启动。ONTAP 工具会使用与升级前相同的 IP 地址注册到 vCenter Server 。

. 如果要使用 IPv6 地址向 vCenter Server 注册 ONTAP 工具，则必须执行以下操作：
+
.. 取消注册 ONTAP 工具。
.. 使用 * 注册 * 页面将 ONTAP 工具的 IPv6 地址注册到 vCenter Server 。
.. 注册后重新生成ONTAP工具和VASA Provider证书。


+

IMPORTANT: 只有 vCenter Server 6.7 及更高版本才支持 IPv6 。

. 注销并重新登录到 vSphere Client 以查看已部署的 ONTAP 工具。
+
.. 从现有 vSphere Web Client 或 vSphere Client 注销并关闭窗口。
.. 登录到 vSphere Client 。
+
在 vSphere Client 中更新此插件可能需要几分钟的时间。





[NOTE]
====
* 从适用于VMware vSphere 9.12及更高版本的ONTAP工具开始、通过证书对ONTAP进行身份验证。您可以添加CA签名证书或自签名证书。请参见、 link:../configure/task_modify_storage_system.html["修改存储系统"] 有关说明，请参见。
* 如果从 ONTAP 工具 7.0 版升级到 ONTAP 工具的最新版本，则必须先创建存储功能配置文件，然后再尝试编辑现有虚拟机存储策略，否则可能会收到错误，指出值不正确或缺失。
* 如果从早期版本的 ONTAP 工具升级到最新版本，则会发现 `vvol.properties 文件中缺少 `vvol.rebalance.threshold` 属性。
+
此属性的默认值设置为85%。*在升级到已启用FIPS的最新ONTAP工具版本后、如果您的vCenter版本较旧、但不支持FIPS、则此部署仍将有效。
但是，如果您将 vCenter 升级到支持 FIPS 的最新版本，并且您使用的是早期版本的 ONTAP 工具，则只有在 vCenter 上禁用了 FIPS 时，部署才会起作用。



====