---
permalink: deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html 
sidebar: sidebar 
keywords: clean up browser cache 
summary: 如果在部署或升级 ONTAP 工具后未自动更新插件，则应清理浏览器和 vCenter Server 上缓存的下载插件包以解决 vCenter Server 插件问题。 
---
= 清除 vSphere 缓存的已下载插件软件包
:icons: font
:imagesdir: ../media/


[role="lead"]
如果在部署或升级 ONTAP 工具后未自动更新插件，则应清理浏览器和 vCenter Server 上缓存的下载插件包以解决 vCenter Server 插件问题。

* 步骤 *

. 从现有 vSphere Web Client 或 vSphere Client 注销。
. 删除浏览器缓存。
. 删除 vSphere Client 缓存的插件软件包。
+
|===


| * 如果使用的是 ...* | * 执行以下操作 ...* 


 a| 
* Windows vCenter Server *
 a| 
删除位于以下位置的以下文件夹 `com.netapp.vasa.vvol.webclient-x.x.x.xxxx` ， `com.netapp.nvpf.webclient-x.x.x.xxxx` 和 `com.netapp.vsch5-x.x.x.xxxx` ：

** vSphere Web Client 路径： `C ： \ProgramData\VMware\vCenterServer\cfg\vsphere-client\vc-packages\vsphere-client-serenity`
** vSphere Client （ HTML5 ）路径： `C ： \ProgramData\VMware\vCenterServer\cfg\vsphere-ui\vc-packages\vsphere-client-serenity`




 a| 
* VCSA *
 a| 
.. 通过 SSH 连接到 VCSA 设备。
.. 使用 `cd /etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity` 将目录更改为 vCenter Web 客户端 UI 扩展目录
.. 使用以下命令删除缓存的插件软件包：
+
....
----
 `rm -rf com.netapp.vasa.vvol.webclient-x.x.x.xxxx`
 `rm -rf com.netapp.nvpf.webclient-x.x.x.xxxx`
 `rm -rf com.netapp.vsch5-x.x.x.xxxx`
----
....
.. 使用 `cd /etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity` 将目录更改为 vCenter Client （ HTML5 ） UI 扩展目录
.. 使用以下命令删除缓存的插件软件包：
+
....
 ----
`rm -rf com.netapp.vasa.vvol.webclient-x.x.x.xxxx`
`rm -rf com.netapp.nvpf.webclient-x.x.x.xxxx`
`rm -rf com.netapp.vsch5-x.x.x.xxxx`
 ----
....


|===
. 使用以下命令登录到 vSphere 并重新启动 vSphere Web Client 和 vSphere Client 服务：
+
[listing]
----
`service-control --stop vsphere-client vsphere-ui`
`service-control --start vsphere-client vsphere-ui`
----

