---
permalink: concepts/reference_metrocluster_configurations_supported_by_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 适用于 VMware vSphere 的 ONTAP 工具支持对 ONTAP 使用 MetroCluster IP 和 FC 配置的环境。大多数情况下，这种支持都是自动提供的。但是、在将MetroCluster环境与适用于VMware vSphere的ONTAP工具和VASA Provider结合使用时、您可能会注意到一些差异。 
---
= ONTAP 工具支持的 MetroCluster 配置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
适用于 VMware vSphere 的 ONTAP 工具支持对 ONTAP 使用 MetroCluster IP 和 FC 配置的环境。大多数情况下，这种支持都是自动提供的。但是、在将MetroCluster环境与适用于VMware vSphere的ONTAP工具和VASA Provider结合使用时、您可能会注意到一些差异。



== MetroCluster配置和ONTAP工具

您必须确保ONTAP工具可以发现主站点和二级站点上的存储系统控制器。通常、适用于VMware vSphere的ONTAP工具会自动发现存储控制器。如果您使用的是集群管理LIF、则最好确认ONTAP工具已发现两个站点上的集群。否则、您可以手动将存储控制器添加到ONTAP工具中。您还可以修改ONTAP工具用于连接到存储控制器的用户名和密码对。

发生切换时，二级站点上的 SVM 将接管。这些 SVM 的名称后面附加了 "` -mc` " 后缀。如果在执行配置数据存储库等操作时发生切换操作，则数据存储库所在 SVM 的名称将更改为包含 "` -mc` " 后缀。发生切回时，此后缀将被丢弃，而主站点上的 SVM 将恢复控制。


NOTE: 如果已将具有MetroCluster配置的SVM用户添加到ONTAP工具中、则在切换后、不会反映SVM名称的更改(即添加了"`-MC`"后缀)。所有其他切换操作将继续正常执行。

发生切换或切回时、ONTAP工具可能需要几分钟的时间来自动检测和发现集群。如果在您执行配置数据存储库等ONTAP工具操作时发生这种情况、则可能会出现延迟。



== MetroCluster 配置和 VASA Provider

VASA Provider 会自动支持使用 MetroCluster 配置的环境。切换在 VASA Provider 环境中是透明的。您不能向VASA Provider添加SVM用户。


NOTE: 在切换后， VASA Provider 不会在二级站点上的 SVM 名称后面附加 "` -mc` " 后缀。



== MetroCluster 配置和SRA

Storage Replication Adapter (SRA)支持使用采用NFS、iSCSI和FCP协议的MetroCluster配置(MCC)的环境。

作为MCC SRA配置的前提条件、所有Storage Virtual Machine (SVM)名称在MCC集群上都应是唯一的。如果名称不唯一、则会导致冲突、并且SRA工作流将失败。

所需操作：

. 在执行MCC切换或切回后、请确保源集群上的_SnapMirror list-目的地_命令使用新的<vserver_name>名称(SVM -MC)显示正确的输出。此命令可能需要长达30分钟才能运行。
. 请先从SRM UI执行发现设备操作、然后再继续执行其他SRA工作流。此操作可确保SRM了解切换或切回后SVM名称发生的更改。

