---
permalink: configure/concept_configure_storage_capability_profiles.html 
sidebar: sidebar 
keywords: storage capability profiles 
summary: 您可以通过适用于 ONTAP 的 VASA Provider 创建存储功能配置文件并将其映射到存储。这有助于您在整个存储中保持一致性。您还可以使用 VASA Provider 检查存储与存储功能配置文件之间的合规性。 
---
= 存储功能配置文件概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过适用于 ONTAP 的 VASA Provider 创建存储功能配置文件并将其映射到存储。这有助于您在整个存储中保持一致性。您还可以使用 VASA Provider 检查存储与存储功能配置文件之间的合规性。

存储功能是一组存储系统属性，用于确定特定级别的存储性能，存储效率以及其他功能，例如与存储功能关联的存储对象的加密。

对于传统数据存储库，您可以使用存储功能配置文件一致地创建具有通用属性的数据存储库，并为其分配 QoS 策略。在配置期间， VSC 会显示与存储功能配置文件匹配的集群， SVM 和聚合。您可以使用存储映射菜单中的 * 全局自动生成配置文件 * 选项从现有传统数据存储库生成存储功能配置文件。创建配置文件后，您可以使用 VSC 监控数据存储库与配置文件的合规性。

如果与 VVOL 数据存储库结合使用，则配置向导可以使用多个存储功能配置文件在数据存储库中创建不同的 FlexVol 卷。您可以使用虚拟机存储策略根据定义自动在适当的 FlexVol 卷中为虚拟机创建 VVOL 。例如，您可以为通用存储类（例如性能限制和加密或 FabricPool 等其他功能）创建配置文件。您可以稍后在 vCenter Server 中创建 VM 存储策略，以表示虚拟机的业务类别，并按名称（例如生产，测试， HR ）将这些策略链接到相应的存储功能配置文件。

与 VVOL 结合使用时，存储功能配置文件还用于设置各个虚拟机的存储性能，并将其放置在 VVOL 数据存储库中最能满足性能要求的 FlexVol 卷上。您可以为性能指定具有最小和 / 或最大 IOPS 的 QoS 策略。您可以在最初配置虚拟机时使用默认策略，也可以在日后业务需求发生变化时更改虚拟机存储策略。此版本的 ONTAP 工具的默认存储功能配置文件：

* AFF_Thick
* FAS_MAX20
* FAS_Default
* AFF_Default
* AFF_Tiering
* AFF_encrypted
* AFF_Encrypted_Tiering
* AFF_Encrypted_Min50
* 白金级
* 铜牌


然后， vCenter Server 会将 LUN 或卷的存储功能与该 LUN 或卷上配置的数据存储库相关联。这样，您就可以在与虚拟机的存储配置文件匹配的数据存储库中配置虚拟机，并确保数据存储库集群中的所有数据存储库都具有相同的存储服务级别。

借助 ONTAP 工具，您可以为每个虚拟卷（ VVol ）数据存储库配置一个新的存储功能配置文件，该配置文件支持在同一个 VVol 数据存储库上配置具有不同 IOPS 要求的虚拟机。在执行具有 IOPS 要求的虚拟机配置工作流时，所有 VVOL 数据存储库都会列在兼容数据存储库列表中。


NOTE: 在尝试为 6.5 之前的 vCenter Server 配置或修改虚拟机时，兼容数据存储库列表中仅会列出包含性能设置为 `MAx_IOPS` 的存储功能配置文件的 VVol 数据存储库。其余 VVOL 数据存储库将列在不兼容的数据存储库列表中。您可以忽略此分类，并从不兼容的数据存储库列表中选择任何 VVOL 数据存储库来配置或修改虚拟机。



== 创建和编辑存储功能配置文件的注意事项

您应了解创建和编辑存储功能配置文件的注意事项。

* 您只能在 AFF 系统上配置最小 IOPS 。
* 您可以在虚拟卷（ VVOL ）数据存储库级别配置 QoS 指标。
+
通过此功能，可以更灵活地为虚拟数据存储库上配置的同一虚拟机的不同 VMDK 分配不同的 QoS 指标。

* 您可以为 FAS 和 AFF 数据存储库配置存储功能配置文件。
+
对于 FAS 和 AFF 系统，您可以将空间预留配置为厚或精简。

* 您可以使用存储功能配置文件为数据存储库提供加密。
* 从适用于 VMware vSphere 的 ONTAP 工具的早期版本升级到最新版本的 ONTAP 工具后，您将无法修改现有存储功能配置文件（在 7.2 版之前创建）。
+
保留原有存储功能配置文件以实现向后兼容性。如果未使用默认模板，则在升级到最新版本的 ONTAP 工具期间，系统会覆盖现有模板，以反映与存储功能配置文件性能相关的新 QoS 指标和分层策略。

* 您不能修改或使用原有存储功能配置文件来配置新的虚拟数据存储库或 VM 存储策略。
* 您必须对所有新数据存储库使用新的存储功能配置文件。

