---
permalink: configure/reference_set_ipv4_or_ipv6.html 
sidebar: sidebar 
keywords:  
summary: 首选项文件kmingoprefs.xml新增 了一个选项、您可以设置此选项来为添加到ONTAP工具的所有存储系统启用IPv4或IPv6支持。 
---
= 使用首选项文件设置 IPv4 或 IPv6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
首选项文件包含用于控制 VMware vSphere 操作的 ONTAP 工具的设置。在大多数情况下，您无需修改这些文件中的设置。了解ONTAP工具使用的首选项文件非常有用。

ONTAP工具具有多个首选项文件。这些文件包含一些输入项和值、用于确定ONTAP工具如何执行各种操作。以下是ONTAP工具使用的一些首选项文件：

` /opt/netapp/vscserver/etc/kamino/kaminoprefs.xml`

` /opt/netapp/vscserver/etc/vsc/vscPreferences.xml`

在某些情况下，您可能需要修改首选项文件。例如、如果您使用iSCSI或NFS、并且ESXi主机和存储系统的子网不同、则必须修改首选项文件。如果不修改首选项文件中的设置、则数据存储库配置将失败、因为ONTAP工具无法挂载数据存储库。

首选项文件中添加了一个新选项 `kaminoprefs.xml` 您可以设置为为为添加到ONTAP工具的所有存储系统启用IPv4或IPv6支持。

* `default.override.option.provision.mount.datastore.address.family` 参数已添加到 `kaminoprefs.xml` 首选项文件中，用于为数据存储库配置设置首选数据 LIF 协议。
+
此首选项适用于添加到ONTAP工具中的所有存储系统。

* 新选项的值为 `IPv4` ， `IPv6` 和 `none` 。
* 默认情况下，此值设置为 `none` 。


|===


| * 值 * | * 问题描述 * 


 a| 
无
 a| 
* 配置使用与用于添加存储的集群或 SVM 管理 LIF 类型相同的 IPv6 或 IPv4 地址类型的数据 LIF 进行。
* 如果 SVM 中不存在相同的 IPv6 或 IPv4 地址类型的数据 LIF ，则会通过其他类型的数据 LIF 进行配置（如果可用）。




 a| 
IPv4
 a| 
* 在选定 SVM 中使用 IPv4 数据 LIF 进行配置。
* 如果 SVM 没有 IPv4 数据 LIF ，则会通过 IPv6 数据 LIF 进行配置（如果此数据 LIF 在 SVM 中可用）。




 a| 
IPv6
 a| 
* 在选定 SVM 中使用 IPv6 数据 LIF 进行配置。
* 如果 SVM 没有 IPv6 数据 LIF ，则会通过 IPv4 数据 LIF 进行配置（如果此数据 LIF 在 SVM 中可用）。


|===
要使用用户界面配置IPv4或IPv6、请参见以下各节：

* link:../configure/add_different_subnets.html["添加不同的子网"]
* link:../configure/task_enable_datastore_mounting_across_different_subnets.html["在不同子网之间启用数据存储库挂载"]

