---
permalink: configure/reference_rebalance_vvols_datastore.html 
sidebar: sidebar 
keywords: vVols datastore,rebalancing 
summary: ONTAP 工具支持使用命令重新平衡数据中心中的 FlexVol 卷。主要目标是在 FlexVol 卷之间实现均匀的空间利用率。ONTAP 工具会根据空间使用情况，精简配置， LUN 计数和存储功能配置文件在现有卷之间重新分布 VVOL 。 
---
= 重新平衡 VVol 数据存储库
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 工具支持使用命令重新平衡数据中心中的 FlexVol 卷。主要目标是在 FlexVol 卷之间实现均匀的空间利用率。ONTAP 工具会根据空间使用情况，精简配置， LUN 计数和存储功能配置文件在现有卷之间重新分布 VVOL 。

VVOL 数据存储库的重新平衡通过 LUN 移动或文件移动来执行。VVOL重新平衡期间考虑的标准如下：

* 不支持NFS VVol数据存储库
* 不会调整现有 FlexVol 卷的大小，也不会添加新的 FlexVol 卷
* 只有具有相同存储功能或卷属性的 FlexVol 卷才会重新平衡
* 考虑重新平衡空间利用率最高的 FlexVol 卷
* 与虚拟机关联的所有 VVOL 都会移至同一个 FlexVol 卷
* LUN 和文件数量限制将保留下来
* 如果 FlexVol 卷之间的空间利用率增量为 10% ，则不会执行重新平衡


rebalance 命令可删除空的 FlexVol 卷，以便为其他数据存储库提供空间。因此，您可以使用命令删除不需要的 FlexVol 卷，以便将其从数据存储库中删除。此命令会将与虚拟机关联的所有 VVol 移动到同一个 FlexVol 卷。在启动重新平衡之前，命令会执行一项预检，以最大程度地减少故障。但是，即使预检成功，一个或多个 VVol 的重新平衡操作也可能失败。如果发生这种情况，则不会回滚重新平衡操作。因此，与虚拟机关联的 VVOL 可能会放置在不同的 FlexVol 卷上，并会生成警告日志。

[NOTE]
====
* 不支持并行数据存储库和虚拟机操作。
* 您必须在每个 VVOL 重新平衡操作完成后执行集群重新发现操作。
* 在 VVol 重新平衡操作期间，如果发现大量 VVol 数据存储库，则传输操作将在设置的默认值之后超时。
+
** 如果发生这种情况，则应修改 `vvol.properties` 文件，将该值设置为 `offtap.operation.timeout.period.seconds=29700` ，然后重新启动 VASA Provider 服务。


* 如果 FlexVol 卷具有快照，则在 VVol 重新平衡操作期间，由于有关空间利用率的详细信息不足， VVol 无法正确重新平衡。
* 您可以将VASA Provider属性_enable．update．vvol.through．discovery_设置为true、以便在容器重新平衡操作期间发生超时时时、在适用于VMware vSphere的ONTAP工具和ONTAP之间获取一致的数据。
* 没有可用于重新平衡VVOV数据存储库的公开REST API。


====
.* 开始之前 *
* 从维护控制台生成Web-CLI令牌：
+
.. 登录到maine控制台。
.. 选择选项*1*设备配置。
.. 选择选项*12*生成Web-CLI验证令牌。


* 从vCenter或Web-CLI获取容器名称和FlexVol卷名称。
要获取连接到容器的FlexVol卷的列表、请从Web-CLI运行命令_container list_。您可以在Web-CLI页面上找到容器重新平衡命令的详细信息。



NOTE: 您需要提供容器名称、以便在连接到该容器的所有FlexVol卷之间执行重新平衡。但是、如果提供了FlexVol卷参数、则只会在提供的FlexVol卷之间执行重新平衡。

.* 步骤 *
. 使用URL从Web-CLI登录 `\https://<OTV-IP>:9083/`
. 运行命令：_container real均势-container_name=container_<container-name>

