---
permalink: configure/task_enable_vasa_provider_for_configuring_virtual_datastores.html 
sidebar: sidebar 
keywords:  
summary: 默认情况下，适用于 VMware vSphere 的 ONTAP 工具已启用 VASA Provider 功能。您可以为每个 VVOL 数据存储库配置具有所需存储功能配置文件的 VMware 虚拟卷 \ （ VVOL\ ）数据存储库。 
---
= 启用 VASA Provider 以配置虚拟数据存储库
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
默认情况下，适用于 VMware vSphere 的 ONTAP 工具已启用 VASA Provider 功能。您可以为每个 VVOL 数据存储库配置具有所需存储功能配置文件的 VMware 虚拟卷（ VVOL ）数据存储库。

* 您需要的内容 *

* 您必须已设置 vCenter Server 实例并配置 ESXi 。
* 您必须已部署 ONTAP 工具。


* 关于此任务 *

如果在升级到 ONTAP Tools 9.7.1 版之前禁用了 VASA Provider 功能，则在升级后， VASA Provider 功能仍会处于禁用状态。此版本允许您为 VVol 数据存储库启用 VVol 复制功能。

* 步骤 *

. 登录到 VMware vSphere 的 Web 用户界面。
. 在 vSphere Client 中，单击 * 菜单 * > * ONTAP Tools Console* 。
. 单击 * 设置 * 。
. 单击管理设置选项卡中的 * 管理功能 * 。
. 在管理功能对话框中，选择要启用的 VASA Provider 扩展。
. 如果要对 VVOL 数据存储库使用复制功能，请使用 * 启用 VVOL 复制 * 切换按钮。
. 输入 ONTAP 工具的 IP 地址和管理员密码，然后单击 * 应用 * 。
+

NOTE: 如果即使在启用 VASA Provider 扩展后， VASA Provider 状态仍显示为 "`脱机` " ，请检查 /var/log/vmware/vmware-sps/sps.log 文件中是否存在与 VASA Provider 的任何连接错误，或者重新启动 "`vmware-sps` " 服务。



如果您使用的是 ONTAP 9.6 或更早版本的集群，则必须向 VASA Provider 注册 OnCommand API 服务，以获取在 SAN VVOL VM 和 SAN VVOL 数据存储库报告中使用的 VVOL 数据存储库和虚拟机的详细信息。但是，如果您使用的是 ONTAP 9.7 或更高版本，则无需向 VASA Provider 注册 OnCommand API 服务。
