---
permalink: configure/task_configure_user_role_and_privileges.html 
sidebar: sidebar 
keywords: user roles 
summary: 您可以使用随 ONTAP 工具和 ONTAP System Manager 提供的 JSON 文件配置新的用户角色来管理存储系统。 
---
= 配置用户角色和权限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用随 ONTAP 工具和 ONTAP System Manager 提供的 JSON 文件配置新的用户角色来管理存储系统。

* 您需要的内容 *

* 您应已按照以下步骤从ONTAP工具下载ONTAP权限文件：
+
** 导航到 `\https://{virtual_appliance_IP}:9083/vsc/config/`
** 下载文件VSC_ONTAP_User_Privileges.zip
** 解压缩下载的VSC_ONTAP_User_Privileges.zip文件
** 访问System Manager
+
请参见知识库文章- https://kb.netapp.com/mgmt/OTV/Virtual_Storage_Console/Virtual_Storage_Console%3A_How_to_retrieve_the_JSON_file_to_configure_user_roles_and_privileges["Virtual Storage Console：如何检索JSON文件以配置用户角色和权限"] 有关如何从WebCLI下载ONTAP权限文件的说明。



* 您应已配置 ONTAP 9.8P1 或更高版本的存储。
* 您应已使用存储系统的管理员权限登录。


* 步骤 *

. 解压缩下载的 ` \https://{virtual_appliance_IP}:9083/vsc/config/VSC_ONTAP_User_Privileges.zip` 文件。
. 访问 ONTAP 系统管理器。
. 单击 * 集群 * > * 设置 * > * 用户和角色 * 。
. 单击 * 添加用户 * 。
. 在添加用户对话框中，选择 * 虚拟化产品 * 。
. 单击 * 浏览 * 以选择并上传 ONTAP 权限 JSON 文件。
+
产品字段会自动填充。

. 从产品功能下拉菜单中选择所需功能。
+
系统会根据选定产品功能自动填充 * 角色 * 字段。

. 输入所需的用户名和密码。
. 选择用户所需的权限（发现，创建存储，修改存储，销毁存储），然后单击 * 添加 * 。


此时将添加新角色和用户，您可以在已配置的角色下查看详细权限。


NOTE: 卸载操作不会删除ONTAP工具角色、但会删除ONTAP工具专用特权的本地化名称、并将前缀附加到"`XXX missing"`。之所以出现此行为，是因为 vCenter Server 不提供删除权限的选项。在重新安装ONTAP工具或升级到更高版本的ONTAP工具时、所有标准ONTAP工具角色和ONTAP工具专用特权都会还原。
