---
permalink: configure/task_set_default_credentials_for_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用适用于 VMware vSphere 的 ONTAP ® 工具为 vCenter Server 中的存储系统设置默认凭据。 
---
= 设置存储系统的默认凭据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用适用于 VMware vSphere 的 ONTAP 工具为 vCenter Server 中的存储系统设置默认凭据。

* 您需要的内容 *

您必须已选择要用于创建默认凭据的 vCenter Server 。

* 关于此任务 *

如果您为存储系统设置了默认凭据、ONTAP工具将使用这些凭据登录到ONTAP工具刚刚发现的存储系统。如果默认凭据不起作用，您必须手动登录到存储系统。ONTAP工具和SRA支持在集群级别或SVM级别添加存储系统凭据。但是， VASA Provider 只能使用集群级别的凭据。

* 步骤 *

. 在 ONTAP 工具的主页页面上，单击 * 设置 * > * 管理设置 * > * 配置存储系统的默认凭据 * 。
. 在存储系统默认凭据对话框中，输入存储系统的用户名和密码。
+
存储控制器凭据会根据用户名和密码对在 ONTAP 中分配。存储控制器凭据可以是管理员帐户，也可以是使用基于角色的访问控制（ Role-Based Access Control ， RBAC ）的自定义帐户。

+
您不能使用ONTAP工具更改与存储控制器的用户名和密码对关联的角色。要修改或创建新的 ONTAP 用户角色以用于 ONTAP 工具，您可以使用 System Manager 。

+
请参见 link:..configure/task_configure_user_role_and_privileges.html["配置用户角色和权限"]部分。

. 单击 * 确定 * 以保存默认凭据。


由于存储系统报告而更新了存储系统凭据 `Authentication Failure` 状态时，应单击“存储系统”页面上的“重新发现全部”选项。执行此操作时、ONTAP工具会尝试使用新凭据连接到存储系统。
