---
permalink: configure/task_add_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: 您可以手动将存储系统添加到 Virtual Storage Console （ VSC\ ）。 
---
= 添加存储系统
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以手动将存储系统添加到 Virtual Storage Console （ VSC ）。


NOTE: 如果ONTAP 集群启用了SAML、则与ONTAP 的通信将通过基本身份验证完成。

* 关于此任务 *

每次启动 Virtual Storage Console （ VSC ）或选择 * 重新发现全部 * 选项时， VSC 都会自动发现可用的存储系统。

* 步骤 *

. 使用ONTAP 工具主页中的任一选项向VSC添加存储系统：
+
** 单击 * 存储系统 * > * 添加 * 。或
** 单击 * 概述 * > * 入门 * ，然后单击添加存储系统下的 * 添加 * 按钮。


. 在 * 添加存储系统 * 对话框中，输入该存储系统的管理 IP 地址和凭据。
+
添加存储系统时、ONTAP 工具插件与存储系统之间的任何通信都应进行相互身份验证。

+
您还可以使用集群或 SVM 的 IPv6 地址添加存储系统。

+
从VSC存储系统页面添加存储时、请指定存储所在的vCenter Server实例。添加存储系统对话框提供了一个下拉列表，其中列出了可用的 vCenter Server 实例。如果要向已与 vCenter Server 实例关联的数据中心添加存储，则 VSC 不会显示此选项。

+
注意

+
** 从ONTAP 工具9.12版本开始、所有ONTAP 存储系统通信都通过基于证书的身份验证进行。
** 如果客户端证书或集群证书无效、则不允许执行删除、调整大小和挂载等传统数据存储库操作。
** 如果客户端证书或集群证书无效、则不允许执行扩展存储、挂载数据存储库等VVOV数据存储库操作。
** 允许执行删除、删除存储和编辑属性等操作、因为这些操作不需要ONTAP 通信。
** 要添加具有SVM范围用户的存储系统，存储系统集群管理员必须编辑该用户，并将身份验证方法*Certification*添加到应用程序HTTP和ONTAPI中。
+
在高级选项中，有两种方法可上载* ONTAP 群集证书*：

+
... *自动提取*-自动提取证书。
... *手动上传*-您需要手动浏览到证书所在的位置并上传证书。




. 添加完所有必需信息后，单击 * 确定 * 。
+
此时将显示Authorize Cluster Certificate (授权集群证书)弹出窗口。

. 单击*显示证书*以查看证书详细信息。单击*是*以添加存储系统

