---
permalink: configure/task_provision_datastores.html 
sidebar: sidebar 
keywords:  
summary: 配置数据存储库会为虚拟机及其虚拟机磁盘（ VMDK\ ）创建一个逻辑容器。您可以配置数据存储库，然后将数据存储库连接到单个主机，集群中的所有主机或数据中心中的所有主机。 
---
= 配置传统数据存储库
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置数据存储库会为虚拟机及其虚拟机磁盘（ VMDK ）创建一个逻辑容器。您可以配置数据存储库，然后将数据存储库连接到单个主机，集群中的所有主机或数据中心中的所有主机。

* 您需要的内容 *

* 要在直接连接到 Virtual Storage Console （ VSC ）的 SVM 上配置数据存储库，必须事先使用具有适当权限的用户帐户（而不是默认 vsadmin 用户帐户或 vsadmin 角色）将 SVM 添加到 VSC 中。
+
您也可以通过添加集群来配置数据存储库。

* 您必须确保在 kaminoprefs.xml 中输入 ESXi 主机连接到的所有网络的子网详细信息。
+
请参见 " 在不同子网之间启用数据存储库挂载 " 。

* 如果您使用 NFS 或 iSCSI ，并且 ESXi 主机和存储系统的子网不同，则 kaminoprefs 首选项文件中的 NFS 或 iSCSI 设置必须包括 ESXi 主机子网掩码。
+
此首选项文件也适用于创建 VVOL 数据存储库。有关详细信息，请参见 _Enable datastore mounting across different subnets_ 和 _Configure the VSC preferences files_ 。

* 如果已启用 VASA Provider ，并且要为 NFS 数据存储库或 VMFS 数据存储库指定存储功能配置文件，则必须已创建一个或多个存储功能配置文件。
* 要创建 NFSv4.1 数据存储库，必须已在 SVM 级别启用 NFSv4.1 。


使用 * 配置数据存储库 * 选项可以为数据存储库指定存储功能配置文件。存储功能配置文件有助于指定一致的服务级别目标（ Service Level Objective ， SLO ）并简化配置过程。只有在启用了 VASA Provider 的情况下，才能指定存储功能配置文件。适用于 VMware vSphere 的 ONTAP 工具支持以下协议：

* NFSv3 和 NFSv4.1
* VMFS5 和 VMFS6


VSC 可以在 NFS 卷或 LUN 上创建数据存储库：

* 对于 NFS 数据存储库， VSC 会在存储系统上创建 NFS 卷，然后更新导出策略。
* 对于 VMFS 数据存储库， VSC 会创建一个新卷（如果选择了该选项，则会使用现有卷），然后创建一个 LUN 和一个 igroup 。


[NOTE]
====
* 如果在运行 ONTAP 9.8 及更高版本的 ASA 和经批准的 AFF 系统中使用 VMFS5 和 VMFS6 数据存储库，则 ONTAP 工具支持将其配置为最大 VMFS LUN 和 64 TB 的卷大小。
+
在其他平台上，支持的最大 LUN 大小为 16 TB 。

* VMware 不支持对数据存储库集群使用 NFSv4.1 。


====
如果在配置期间未指定存储功能配置文件，您可以稍后使用存储映射页面将数据存储库映射到存储功能配置文件。您可以对 FlexGroup 支持的数据存储库上配置的虚拟机的数据 VMDK 文件应用存储服务质量设置，吞吐量上限（最大 IOPS ）和吞吐量下限（最小 IOPS ）。可以通过右键单击数据存储库在数据存储库级别或单个虚拟机级别应用 QoS 设置。右键单击选项仅适用于由 FlexGroup 数据存储库提供支持的数据存储库或虚拟机。将 QoS 应用于数据存储库后，任何已存在的数据存储库或虚拟机 QoS 设置将被覆盖。无法在数据存储库级别或虚拟机级别为直接 SVM 上配置的数据存储库应用 QoS 设置，因为 ONTAP 在 SVM 管理级别不支持 QoS 。

* 步骤 *

. 您可以使用以下方法之一访问数据存储库配置向导：
+
|===


| * 如果选择 "from..." | * 执行以下操作 ...* 


 a| 
vSphere Client 主页
 a| 
.. 单击 * 主机和集群 * 。
.. 在导航窗格中，选择要配置数据存储库的数据中心。
.. 要指定要挂载数据存储库的主机，请参见下一步。




 a| 
ONTAP 工具主页
 a| 
.. 单击 * 概述 * 。
.. 单击 * 入门 * 选项卡。
.. 单击 * 配置 * 按钮。
.. 单击 * 浏览 * 以选择要按下一步配置数据存储库的目标。


|===
. 指定要挂载数据存储库的主机。
+
|===


| * 使数据存储库可供使用 ...* | * 执行此操作 ...* 


 a| 
数据中心中的所有主机
 a| 
右键单击某个数据中心，然后选择 * NetApp ONTAP Tools* > * 配置数据存储库 * 。



 a| 
集群中的所有主机
 a| 
右键单击主机集群，然后选择 * NetApp ONTAP Tools* > * 配置数据存储库 * 。



 a| 
一台主机
 a| 
右键单击某个主机，然后选择 * NetApp ONTAP tools* > * 配置数据存储库 * 。

|===
. 填写新建数据存储库对话框中的字段以创建数据存储库。
+
对话框中的大多数字段都是不言自明的。下表介绍了一些可能需要指导的字段。

+
|===


| * 第节 * | * 问题描述 * 


 a| 
常规
 a| 
" 新建数据存储库配置 " 对话框的 " 常规 " 部分提供了用于输入新数据存储库的目标，名称，大小，类型和协议的选项。您可以选择 * NFS * 或 * VMFS* 协议来配置传统数据存储库。此版本允许您配置最大大小为 64 TB 的 VMFS 数据存储库。您可以 `D选项 " 在 ONTAP 集群中分布数据存储库数据` " ，以便在存储系统上配置 FlexGroup 卷。选择此选项会自动取消选中复选框 "`Use Storage Capability Profile for provisioning` " 。对于 FlexGroup 数据存储库配置，仅会列出 9.8 及更高版本的 ONTAP 集群以供选择。VVOL 数据存储库类型用于配置 VVOL 数据存储库。如果启用了 VASA Provider ，则还可以决定是否使用存储功能配置文件。* 数据存储库集群 * 选项仅适用于传统数据存储库。您应使用 * 高级 * 选项指定 * VMFS5* 或 * VMFS6* 文件系统。



 a| 
存储系统
 a| 
如果您在常规部分中选择了相应选项，则可以选择列出的存储功能配置文件之一。如果要配置 FlexGroup 数据存储库，则不支持此数据存储库的存储功能配置文件。存储系统和 Storage Virtual Machine 的系统建议值已填充，以便于使用。但是，如果需要，您可以修改这些值。



 a| 
存储属性
 a| 
默认情况下， VSC 会填充 * 聚合 * 和 * 卷 * 选项的建议值。您可以根据自己的要求自定义这些值。FlexGroup 数据存储库不支持选择聚合，因为 ONTAP 负责管理聚合选择。此外，还会填充 * 高级 * 菜单下的 * 空间预留 * 选项，以获得最佳结果。



 a| 
摘要
 a| 
您可以查看为新数据存储库指定的参数摘要。摘要页面中提供了一个新字段 "`卷模式` " ，用于区分创建的数据存储库类型。"`卷模式` " 可以是 "`FlexVol` " 或 "`FlexGroup` " 。

|===



NOTE: 传统数据存储库中的 FlexGroup 不能缩减到低于现有大小，但最大可增长 120% 。在这些 FlexGroup 卷上启用默认快照。。在摘要部分中，单击 * 完成 * 。

* 相关信息 *

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Virtual_Storage_Console_for_VMware_vSphere/Datastore_inaccessible_when_volume_status_is_changed_to_offline["当卷状态更改为脱机时，无法访问数据存储库"]
