---
permalink: configure/task_provision_vvols_datastores.html 
sidebar: sidebar 
keywords:  
summary: 只有在 ONTAP 工具中启用了 VASA Provider 的情况下，才能使用配置数据存储库向导配置 VVOL 数据存储库。 
---
= 配置 VVOL 数据存储库
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
只有在 ONTAP 工具中启用了 VASA Provider 的情况下，才能使用配置数据存储库向导配置 VVOL 数据存储库。

* 您需要的内容 *

* 您应确保在 Kaminoprefs.xml 中输入 ESXi 托管的连接到的所有网络的子网详细信息。
+
请参见 * 在不同子网之间启用数据存储库挂载 * 一节。

* 您应在源站点和目标站点的数据存储库上配置类似的复制策略和计划，以便成功执行反向复制。


通过配置数据存储库菜单，您可以为数据存储库指定存储功能配置文件，此配置文件有助于指定一致的服务级别目标（ Service Level Objective ， SLO ）并简化配置过程。只有在启用了 VASA Provider 的情况下，才能指定存储功能配置文件。

只有在运行 ONTAP 9.5 或更高版本时，用作后备存储的 FlexVol 卷才会显示在 VVOL 信息板上。您不应使用 vCenter Server 的 " 新建数据存储库 " 向导配置 VVOL 数据存储库。

* 您必须使用集群凭据创建 VVOL 数据存储库。
+
您不能使用 SVM 凭据创建 VVOL 数据存储库。

* VASA Provider 不支持将一个协议的 VVOL 数据存储库上托管的虚拟机克隆到另一个使用不同协议的数据存储库。
* 您应已在源站点和目标站点上完成集群配对和 SVM 配对。


* 关于此任务 *


NOTE: ONTAP 工具 9.10 版支持为全 SAN 阵列（ ASA ）类型的 ONTAP 9.9.1 或更高版本的存储平台创建 vmdk 大小大于 16 TB 的 VVOL 数据存储库。

* 步骤 *

. 在 vSphere Client 主页页面中，单击 * 主机和集群 * 。
. 在导航窗格中，选择要配置数据存储库的数据中心。
. 指定要挂载数据存储库的主机。
+
|===


| * 使数据存储库可供使用 ...* | * 执行此操作 ...* 


 a| 
数据中心中的所有主机
 a| 
右键单击某个数据中心，然后选择 * NetApp VSC* > * 配置数据存储库 * 。



 a| 
集群中的所有主机
 a| 
右键单击某个集群，然后选择 * NetApp VSC* > * 配置数据存储库 * 。



 a| 
一台主机
 a| 
右键单击某个主机，然后选择 * NetApp VSC* > * 配置数据存储库 * 。

|===
. 填写新建数据存储库对话框中的字段以创建数据存储库。
+
对话框中的大多数字段都是不言自明的。下表介绍了一些可能需要指导的字段。

+
|===


| * 第节 * | * 问题描述 * 


 a| 
常规
 a| 
" 新建数据存储库 " 对话框的 " 常规 " 部分提供了用于输入新数据存储库的位置，名称，问题描述，类型和协议的选项。VVOL 数据存储库类型用于配置 VVOL 数据存储库。


NOTE: 如果要为 VVOL 复制配置 iSCSI VVOL 数据存储库，则在目标站点上创建 VVOL 数据存储库之前，需要执行 SnapMirror 更新和集群重新发现。



 a| 
存储系统
 a| 
通过此部分，您可以选择是要使 VVol 数据存储库启用还是禁用复制。此版本仅允许使用异步类型复制配置文件。然后，您可以选择列出的一个或多个存储功能配置文件。系统会自动填充已配对 * 存储系统 * 和 * 存储虚拟机 * 的系统建议值。只有在 ONTAP 中配对后，才会填充建议值。您可以根据需要修改这些值。

* 注： * 在 ONTAP 中创建 FlexVol 卷时，应确保使用要在存储功能配置文件中选择的属性创建这些卷。读写和数据保护 FlexVol 卷都应具有类似的属性。

创建 FlexVol 卷并在 ONTAP 中初始化 SnapMirror 后，您应在 VSC 中运行存储重新发现，以便能够查看新卷。



 a| 
存储属性
 a| 
您应从现有列表中选择 SnapMirror 计划以及所需的 FlexVol 卷。此计划应与在 VM 存储策略页面中选择的计划类似。用户应已使用列出的 SnapMirror 在 ONTAP 上创建 FlexVol 卷。您可以使用 * 默认存储功能配置文件 * 选项选择用于创建 VVOL 的默认存储功能配置文件。默认情况下，所有卷都会设置为 Maximum Autogrow Size （最大自动增长大小）为 120 % ，并在这些卷上启用默认 Snapshot 。

* 注： *

** 属于 VVOL 数据存储库的 FlexVol 卷不能缩减到低于现有大小，但最多可增长 120% 。此 FlexVol 卷上已启用默认快照。
** 应创建的 FlexVol 卷的最小大小为 5 GB 。


|===
. 在摘要部分中，单击 "**Finish" 。


* 结果 *

配置 VVOL 数据存储库后，会在后端创建复制组。

* 相关信息 *

link:../manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html["使用 VVol 信息板分析性能数据"]
