---
permalink: manage/concept_what_vasa_provider_reports_do.html 
sidebar: sidebar 
keywords: VSC, VASA Provider, and SRA 
summary: VVOL 报告可显示有关 VMware 虚拟卷 \ （ VVol\ ）数据存储库以及在这些数据存储库上创建的虚拟机的详细信息。您可以通过 VVOL 信息板查看和确定 vCenter Server 中 VVOL 数据存储库和虚拟机的潜在问题。 
---
= VVOL 报告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VVOL 报告可显示有关 VMware 虚拟卷（ VVOL ）数据存储库以及在这些数据存储库上创建的虚拟机的详细信息。您可以通过 VVOL 信息板查看和确定 vCenter Server 中 VVOL 数据存储库和虚拟机的潜在问题。

您可以查看，组织和导出报告。VVOL 数据存储库和虚拟机报告的数据由 ONTAP 以及 OnCommand API 服务提供。

VVOL 提供了以下预制报告：

* VVOL 数据存储库报告
* VVOL VM 报告


* VVOL 数据存储库报告 *

+ "VVol 数据存储库报告 " 菜单提供了有关数据存储库的以下参数的信息：

* VVOL 数据存储库名称
* 可用空间
* 已用空间
* 总空间
* 已利用空间的百分比
* 可用空间百分比
* IOPS
* ONTAP 9.8 及更高版本上基于 NFS 的 VVOL 数据存储库提供了延迟性能指标。您还可以验证生成报告的时间。您可以通过 VVol 数据存储库报告菜单根据需要组织报告，然后使用 * 导出到 CSV* 按钮导出组织的报告。报告中的每个 SAN VVol 数据存储库名称都是一个链接，可导航到选定 SAN VVol 数据存储库的 "Monitor" 选项卡，您可以使用此选项卡查看性能指标。


* VVOL 虚拟机报告 *

+ VVOL 虚拟机摘要报告菜单提供了使用适用于选定 vCenter Server 的 VASA Provider 为 ONTAP 配置的 SAN VVOL 数据存储库的所有虚拟机的性能指标。VM 报告中显示的虚拟机指标是指 VVol 数据存储库上的虚拟机每 10 分钟收集一次的历史数据。将 "`上次刷新时间` 和 "`下一次刷新时间` " 添加到表中，以提供有关何时收集数据以及下次收集数据的时间的信息。

* 虚拟机的名称
* 已提交容量
* 正常运行时间
* IOPS
* 吞吐量
+
此报告将显示虚拟机是已启动还是已关闭。

* 逻辑空间
* 主机
* 电源状态
* 延迟
+
此报告将显示与虚拟机关联的所有 VVol 数据存储库中虚拟机的延迟。



报告中的每个虚拟机名称都是指向选定虚拟机的 " 监控 " 选项卡的链接。您可以根据需要组织虚拟机报告，以 .CSV 格式导出报告，然后将报告保存在本地系统上。报告的时间戳将附加到已保存的报告中。
