---
permalink: manage/concept_virtual_storage_console_reports.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用 ONTAP 工具控制台报告菜单查看特定 vCenter Server 中选定 VSC 实例管理的所有数据存储库的预定义报告。您可以执行排序和导出报告等操作。 
---
= ONTAP 工具数据存储库和 VVOL 报告概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP 工具控制台 * 报告 * 菜单查看特定 vCenter Server 中选定 VSC 实例管理的所有数据存储库的预定义报告。您可以执行排序和导出报告等操作。

报告可显示有关数据存储库和虚拟机的详细信息，使您可以查看和确定 vCenter Server 中数据存储库和虚拟机的潜在问题

您可以查看，排序和导出报告。

Virtual Storage Console （ VSC ）提供了以下预定义报告：

* 数据存储库报告
* 虚拟机报告
* VVOL 数据存储库报告
* VVOL 虚拟机报告




== 数据存储库报告

数据存储库报告提供了有关传统数据存储库以及在这些数据存储库上创建的虚拟机的详细信息。

通过传统信息板，您可以查看和确定 vCenter Server 中的数据存储库和虚拟机可能存在的问题。您可以查看，排序和导出报告。传统数据存储库和虚拟机报告的数据由 vCenter Server 提供。但是，由于引入了 FlexGroup 支持的数据存储库支持，因此会从 ONTAP 获取一些指标，例如延迟，吞吐量和 IOPS 。


NOTE: 直接存储虚拟机（ SVM ）上配置的 FlexGroup 数据存储库不支持文件监控。

数据存储库提供以下预定义报告：

* 数据存储库报告
* 虚拟机报告


* 数据存储库报告 *

数据存储库报告菜单提供了有关数据存储库的以下参数的信息：

* 数据存储库的名称
* 数据存储库的类型： NFS 或 VMFS
* 卷模式
+
卷模式可以是 FlexVol 卷，也可以是 FlexGroup 卷。

* 可用空间
* 已用空间
* 总空间
* 已利用空间的百分比
* 可用空间百分比
* IOPS
+
此报告将显示数据存储库的 IOPS 。

* 延迟
+
此报告将显示数据存储库的延迟信息。

+
您还可以验证生成报告的时间。通过数据存储库报告菜单，您可以根据需要对报告进行组织，然后使用 * 导出到 CSV* 按钮导出已组织的报告。报告中的数据存储库名称是导航到选定数据存储库的 " 监控 " 选项卡的链接，您可以在此查看数据存储库性能指标。



* 虚拟机报告 *

虚拟机报告菜单提供了使用 VSC 为选定 vCenter Server 配置的数据存储库的所有虚拟机的性能指标。虚拟机报告中显示的虚拟机指标是指传统数据存储库上的虚拟机每 30 分钟收集一次的历史数据。" 上次刷新时间 " 和 " 下次刷新时间 " 将添加到表中，以提供有关数据收集时间以及下次数据收集时间的详细信息。

* 虚拟机的名称
* 数据存储库名称
* 卷模式
+
卷模式可以是 FlexVol 卷，也可以是 FlexGroup 卷。

* 源
+
用于收集虚拟机详细信息的源可以是 ONTAP 或 vCenter Server 。

* 延迟
+
此报告将显示与虚拟机关联的所有数据存储库中虚拟机的延迟。

* IOPS
* 吞吐量
* 已提交容量
+
此报告将显示虚拟机的已提交容量值。

* 主机
+
此报告将显示虚拟机可用的主机系统。

* 正常运行时间
+
此报告将显示虚拟机启动的时间以及 ESXi 主机上可用的时间。

* 电源状态
+
此报告将显示虚拟机是已启动还是已关闭。



报告中的每个虚拟机名称都是指向选定虚拟机的 " 监控 " 选项卡的链接。您可以根据需要对虚拟机报告进行排序，并将报告导出为 .CSV 文件，然后将报告保存在本地系统上。报告的时间戳也会附加到保存的报告中。

对于由 FlexGroup 卷提供支持的虚拟机，打开新虚拟机的电源后，文件将在 ONTAP 上注册以进行监控。从 ONTAP 访问 VM 报告时，将获取延迟，吞吐量和 IOPS 的历史指标。



== VVOL 报告

VVOL 报告可显示有关 VMware 虚拟卷（ VVOL ）数据存储库以及在这些数据存储库上创建的虚拟机的详细信息。您可以通过 VVOL 信息板查看和确定 vCenter Server 中 VVOL 数据存储库和虚拟机的潜在问题。

您可以查看，组织和导出报告。VVOL 数据存储库和虚拟机报告的数据由 ONTAP 以及 OnCommand API 服务提供。

VVOL 提供了以下预制报告：

* VVOL 数据存储库报告
* VVOL VM 报告


* VVOL 数据存储库报告 *

"VVol 数据存储库报告 " 菜单提供了有关数据存储库的以下参数的信息：

* VVOL 数据存储库名称
* 可用空间
* 已用空间
* 总空间
* 已利用空间的百分比
* 可用空间百分比
* IOPS
* ONTAP 9.8 及更高版本上基于 NFS 的 VVOL 数据存储库提供了延迟性能指标。您还可以验证生成报告的时间。您可以通过 VVol 数据存储库报告菜单根据需要组织报告，然后使用 * 导出到 CSV* 按钮导出组织的报告。报告中的每个 SAN VVol 数据存储库名称都是一个链接，可导航到选定 SAN VVol 数据存储库的 "Monitor" 选项卡，您可以使用此选项卡查看性能指标。


* VVOL 虚拟机报告 *

"VVol 虚拟机摘要报告 " 菜单提供了使用适用于 ONTAP 的 VASA Provider 为选定 vCenter Server 配置的 SAN VVol 数据存储库的所有虚拟机的性能指标。VM 报告中显示的虚拟机指标是指 VVol 数据存储库上的虚拟机每 10 分钟收集一次的历史数据。表中将添加 " 上次刷新时间 " 和 " 下次刷新时间 " ，以提供有关何时收集数据以及下次收集数据的信息。

* 虚拟机的名称
* 已提交容量
* 正常运行时间
* IOPS
* 吞吐量
+
此报告将显示虚拟机是已启动还是已关闭。

* 逻辑空间
* 主机
* 电源状态
* 延迟
+
此报告将显示与虚拟机关联的所有 VVol 数据存储库中虚拟机的延迟。



报告中的每个虚拟机名称都是指向选定虚拟机的 " 监控 " 选项卡的链接。您可以根据需要组织虚拟机报告，以 ` .CSV` 格式导出报告，然后将报告保存在本地系统上。报告的时间戳将附加到已保存的报告中。
