---
permalink: manage/concept_datastore_reports.html 
sidebar: sidebar 
keywords: Datastore Reports 
summary: 数据存储库报告提供了有关传统数据存储库以及在这些数据存储库上创建的虚拟机的详细信息。 
---
= 数据存储库报告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
数据存储库报告提供了有关传统数据存储库以及在这些数据存储库上创建的虚拟机的详细信息。

通过传统信息板，您可以查看和确定 vCenter Server 中的数据存储库和虚拟机可能存在的问题。您可以查看，排序和导出报告。传统数据存储库和虚拟机报告的数据由 vCenter Server 提供。但是，由于引入了 FlexGroup 支持的数据存储库支持，因此会从 ONTAP 获取一些指标，例如延迟，吞吐量和 IOPS 。


NOTE: 直接存储虚拟机（ SVM ）上配置的 FlexGroup 数据存储库不支持文件监控。

数据存储库提供以下预定义报告：

* 数据存储库报告
* 虚拟机报告


* 数据存储库报告 *

+ 数据存储库报告菜单可提供有关数据存储库的以下参数的信息：

* 数据存储库的名称
* 数据存储库的类型： NFS 或 VMFS
* 卷模式
+
卷模式可以是 FlexVol 卷，也可以是 FlexGroup 卷。

* 可用空间
* 已用空间
* 总空间
* 已利用空间的百分比
* 可用空间百分比
* IOPS
+
此报告将显示数据存储库的 IOPS 。

* 延迟
+
此报告将显示数据存储库的延迟信息。

+
您还可以验证生成报告的时间。通过数据存储库报告菜单，您可以根据需要对报告进行组织，然后使用 * 导出到 CSV* 按钮导出已组织的报告。报告中的数据存储库名称是导航到选定数据存储库的 " 监控 " 选项卡的链接，您可以在此查看数据存储库性能指标。



* 虚拟机报告 *

+ "Virtual Machine Report" 菜单提供了使用 VSC 为选定 vCenter Server 配置的数据存储库的所有虚拟机的性能指标。虚拟机报告中显示的虚拟机指标是指传统数据存储库上的虚拟机每 30 分钟收集一次的历史数据。此时，表中将添加 "`上次刷新时间` " 和 "`下一次刷新时间 ` " ，以提供有关何时收集数据以及下次收集数据的详细信息。

* 虚拟机的名称
* 数据存储库名称
* 卷模式
+
卷模式可以是 FlexVol 卷，也可以是 FlexGroup 卷。

* 源
+
用于收集虚拟机详细信息的源可以是 ONTAP 或 vCenter Server 。

* 延迟
+
此报告将显示与虚拟机关联的所有数据存储库中虚拟机的延迟。

* IOPS
* 吞吐量
* 已提交容量
+
此报告将显示虚拟机的已提交容量值。

* 主机
+
此报告将显示虚拟机可用的主机系统。

* 正常运行时间
+
此报告将显示虚拟机启动的时间以及 ESXi 主机上可用的时间。

* 电源状态
+
此报告将显示虚拟机是已启动还是已关闭。



报告中的每个虚拟机名称都是指向选定虚拟机的 " 监控 " 选项卡的链接。您可以根据需要对虚拟机报告进行排序，并将报告导出为 .CSV 文件，然后将报告保存在本地系统上。报告的时间戳也会附加到保存的报告中。

对于由 FlexGroup 卷提供支持的虚拟机，打开新虚拟机的电源后，文件将在 ONTAP 上注册以进行监控。从 ONTAP 访问 VM 报告时，将获取延迟，吞吐量和 IOPS 的历史指标。
