---
permalink: manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用 ONTAP 工具的 VVol 信息板根据所选参数监控性能并查看 vCenter Server 中排名前五位的 SAN 和 NAS VMware 虚拟卷（ VVols ）数据存储库。 
---
= 使用 VVol 信息板分析性能数据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP 工具的 VVol 信息板根据所选参数监控性能并查看 vCenter Server 中排名前五位的 SAN 和 NAS VMware 虚拟卷（ VVol ）数据存储库。

* 您需要的内容 *

* 如果您使用的是 ONTAP 9.6 或更早版本，则应已启用 OnCommand API 服务 2.1 或更高版本。
+
您无需向 VASA Provider 注册 OnCommand API 服务即可获取 ONTAP 9.7 或更高版本的 SAN VVOL 数据存储库或 SAN VVOL VM 数据存储库报告的详细信息。

+
https://mysupport.netapp.com/site/global/dashboard[]

* 您的存储系统应使用 ONTAP 9.3 或更高版本。


ONTAP 提供的 IOPS 数据将进行四舍五入并显示在 VVOL 信息板上。ONTAP 提供的实际 IOPS 值与 VVol 信息板上显示的 IOPS 值之间可能存在差异。ONTAP 工具可为基于 NFS 的 VVOL 数据存储库提供性能监控。


NOTE: 如果您是首次注册 OnCommand API 服务，则只能在 15 到 30 分钟后在 VVOL 信息板上查看 SAN VVOL 数据存储库的所有性能指标数据。

* VVOL 信息板数据每 10 分钟定期刷新一次。
* 如果您已在 vCenter Server 实例中添加，修改或删除存储系统，则可能在一段时间内不会注意到 VVol 信息板上的数据发生任何更改。
+
这是因为 OnCommand API 服务需要一些时间才能从 ONTAP 获取更新的指标。

* VVol 信息板的 " 概述 " portlet 中显示的总 IOPS 值不是 " 读取 IOPS" 值和 " 写入 IOPS" 值的累积值。
+
" 读取 IOPS" ， " 写入 IOPS" 和 " 总 IOPS" 是由 OnCommand API 服务提供的单独指标。如果 OnCommand API 服务提供的总 IOPS 值与累积 IOPS 值（读取 IOPS 值 + 写入 IOPS 值）之间存在差异，则 VVOL 信息板上的 IOPS 值也会出现相同的差异。

* 在 ONTAP 9.8 及更高版本上配置的基于 NFS 的数据 VVOL 会自动注册到 VVOL 信息板中进行性能监控。


* 步骤 *

. 在 vSphere Client 主页页面中，单击 * ONTAP tools* 。
. 使用 * vCenter server* 下拉菜单选择所需的 vCenter Server 以查看数据存储库。
. 单击 * VVOL 信息板 * 。
+
数据存储库 portlet 可提供以下详细信息：

+
** vCenter Server 实例中由 VASA Provider 管理的 VVOL 数据存储库的数量
** 根据资源使用情况和性能参数，您可以根据已用空间， IOPS 或延迟以及所需顺序更改数据存储库列表的前五个 VVol 数据存储库。


. 使用虚拟机 portlet 查看虚拟机的详细信息。
+
虚拟机 portlet 可提供以下详细信息：

+
** 在 vCenter Server 中使用 ONTAP 数据存储库的虚拟机数量
** 根据 IOPS ，延迟，吞吐量，已提交容量，正常运行时间， 和逻辑空间您可以自定义前五个虚拟机在 VVOL 信息板中的列出方式。






== VVOL 信息板数据要求

要显示 VMware 虚拟卷（ VVOL ）数据存储库和虚拟机的动态详细信息，您必须验证 VVOL 信息板的一些重要要求。

下表概述了在 VVol 信息板未显示已配置 SAN VVol 数据存储库和虚拟机的性能指标时应验证的内容。

|===


| * 注意事项 * | * 问题描述 * 


 a| 
首次部署 OnCommand API 服务
 a| 
* 如果使用的是 ONTAP 集群 9.6 或更早版本，则使用的是 OnCommand API 服务 2.1 或更高版本。
+
如果您使用的是 ONTAP 9.7 及更高版本，则无需向 VASA Provider 注册 OnCommand API 服务。

* 从 OnCommand 支持站点下载并安装 OnCommand API 服务后，您必须按照 _NetApp API 服务安装和设置指南 _ 中提供的安装说明进行操作。
* 每个 VASA Provider 实例都必须有一个专用的 OnCommand API 服务实例。
+
OnCommand API 服务不得在多个 VASA Provider 实例或 vCenter Server 之间共享。

* OnCommand API 服务正在运行且可访问。




 a| 
存储系统
 a| 
* 您正在使用 ONTAP 9.3 或更高版本。
* 您正在为存储系统使用适当的凭据。
* 您的存储系统处于活动状态且可访问。
* 选定虚拟机必须至少使用一个 VVOL 数据存储库，并且 I/O 操作正在该虚拟机的磁盘上执行。


|===